// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package info.share.portal.domain;

import info.share.portal.domain.TaskDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TaskDataOnDemand_Roo_Configurable {
    
    declare @type: TaskDataOnDemand: @Configurable;
    
}
